### ISSUE TITLE
Can't start SEB

### ISSUE THREAD

**Issue by dkummer63** [SafeExamBrowser/seb-win-refactoring#584] opened 2023-03-20 15:40 UTC
I have a student with a HP Windows-Book, Win 11, that has problems with starting SEB. There is an error occuring, as shown in the window. The log-Ffile is attached. 
Thanks for any help
[2023-03-20_16h16m17s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/11020055/2023-03-20_16h16m17s_Client.log)
[2023-03-20_16h16m17s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/11020057/2023-03-20_16h16m17s_Runtime.log)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/89595743/226391763-20638480-b499-47f3-b8db-82e1c3de54b0.png)

Daniel

**Comment by dbuechel** [comment] 2023-03-22 11:17
There appears to be an issue with the communication between SEB's application components:

```
2023-03-20 16:16:18.958 [01] - INFO: Initializing runtime connection...
2023-03-20 16:16:18.958 [01] - DEBUG: [RuntimeProxy] Trying to connect to endpoint 'net.pipe://localhost/safeexambrowser/runtime/1a10a67c-4171-428b-a5d9-8c7ba281a6e0' with authentication token '3a6cd1f2-65a1-4e8f-85de-4be2d246c5c5'...
2023-03-20 16:16:19.005 [01] - DEBUG: [RuntimeProxy] Communication channel is opening...
2023-03-20 16:16:19.021 [01] - WARNING: [RuntimeProxy] Communication channel has faulted!
2023-03-20 16:16:19.036 [01] - WARNING: [RuntimeProxy] Endpoint 'net.pipe://localhost/safeexambrowser/runtime/1a10a67c-4171-428b-a5d9-8c7ba281a6e0' could not be found!
2023-03-20 16:16:19.036 [01] - ERROR: Failed to connect to the runtime. Aborting startup...
```

Could you please check the system logs of Windows itself (in the Event Viewer or Ereignisanzeige system application) whether there are any errors or warnings related to SEB?

**Comment by dkummer63** [comment] 2023-03-22 12:52
I ask the student.

**Comment by tanmaya-hub** [comment] 2023-04-17 17:01
I am facing exactly the same WCF Endpoint  issue. I am using  windows-10 OS and SEB version 3.3.1. I have gone through the log files and found the following things from the log files.


  (1):- The SEB Runtime app opened.  Successfully started communication host for the endpoint of Runtime.
  (2):- The SEB Runtime app could able to communicate with the Endpoint of SEB service and initiated the SEB session.
  (3):- Then SEB Client app opened and it tried to communicate with SEB Runtime by calling the Endpoint of SEB RunTime.
        SEB Client app could not able to contact the Endpoint of SEB Runtime. But SEB RunTime Endpoint was available. Because 
        from the logs of the RunTime App it is clear that the Endpoint of SEB Runtime was closed after SEB Client app got closed.

I have attached the log files. This issue is occuring in the latest version of SEB as well as in the older versions of SEB.
This WCF Endpoint issue is occuring in one machine not in other, when both machines have identical system security setttings like anti-virus, Firewall and user privilages. Kindly give a fix for this WCF Endpoint 
[2023-04-17_09h48m51s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/11253372/2023-04-17_09h48m51s_Client.log)
[2023-04-17_09h48m51s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/11253373/2023-04-17_09h48m51s_Runtime.log)
issue.

**Comment by HugoExceptOnFire** [comment] 2023-04-27 11:30
We're having the same problem here, can't see anything relevent looking in the event log.
It works if I launch SEB as an Administrator, not sure what the issue could be.

**Comment by dbuechel** [comment] 2023-04-27 11:38
>It works if I launch SEB as an Administrator, not sure what the issue could be.

That would then however indicate that you have a configuration / access right issue on your system(s). Did you verify that you don't have any group policies or other system configurations / access right restrictions in place that would prevent SEB from being able to use Inter-Process Communication (IPC) via the .NET WCF framework?

**Comment by dbuechel** [comment] 2023-04-27 11:39
Or maybe you're using some third-party anti-virus or other related security software that would interfere or restrict SEB from being able to use IPC between its application components?

**Comment by HugoExceptOnFire** [comment] 2023-04-27 11:41
> Or maybe you're using some third-party anti-virus or other related security software that would interfere or restrict SEB from being able to use IPC between its application components?

We're using Sophos Central but I tried disabling it.
We have a number of GPOs in place but the difficult part is I have two laptops in the same configuration, one works and the other doesn't so just trying to figure out what could be different between them.

**Comment by dbuechel** [comment] 2023-04-28 09:41
> We have a number of GPOs in place but the difficult part is I have two laptops in the same configuration, one works and the other doesn't.

That again would strongly indicate, as you correctly stated, that there indeed may be a difference in the configuration or another aspect between these systems. So it definitely would be the best first step to try to find what that difference could be.

**Comment by tanmaya-hub** [comment] 2023-05-01 13:27
I have also observed the same. When SEB is launched as administrator, SEB runs without any issue. But when SEB runs as standard user, the "Endpoint .... not found!" issue is occuring. Because the SEB Client app can not able to communicate with the Endpoint of SEB Runtime. No relevant information is found from the system event log.  Has anybody able to find the difference in the system configurations (Group Policy Objects/ Users privilages)  or any other solution for this issue?

**Comment by dkummer63** [comment] 2023-05-01 14:03
I have now finally been able to test it again with the student, and the only error protocoll in the Ereignisanzeige is the following. We started an exam.net-Exam with SEB in the background, the error occurred and then we found the following error protocol: 
[Protokollname_SEB.docx](https://github.com/SafeExamBrowser/seb-win-refactoring/files/11365746/Protokollname_SEB.docx)




**************************
Protokollname: Application
Quelle:        Windows Error Reporting
Datum:         01.05.2023 15:49:34
Ereignis-ID:   1001
Aufgabenkategorie:Keine
Ebene:         Informationen
Schlüsselwörter:
Benutzer:      LAPTOP-734P5RIS\Test
Computer:      LAPTOP-734P5RIS
Beschreibung:
Fehlerbucket 2044503629279316353, Typ 5
Ereignisname: RADAR_PRE_LEAK_64
Antwort: Nicht verfügbar
CAB-Datei-ID: 0

Problemsignatur:
P1: PhoneExperienceHost.exe
P2: 1.23022.140.0
P3: 10.0.22621.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Angefügte Dateien:
\\?\C:\Users\Test\AppData\Local\Temp\RDR54DC.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c07db6d1-0327-48db-9036-1a1b7483d601.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.aa0da1b3-171b-46d3-a1fc-a3e93c31bdc0.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e3e3969d-9645-4caa-a0a2-ea4548342e23.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.655a6083-daf1-4c0c-90b2-09e06cbe5004.tmp.xml

Diese Dateien befinden sich möglicherweise hier:
NULL

Analysesymbol: 
Es wird erneut nach einer Lösung gesucht: 0
Berichts-ID: cc09e839-5630-4b47-b2fc-e343e307ce79
Berichtstatus: 268435456
Bucket mit Hash: 90e1571cefddc9387c5f8937f530c981
CAB-Datei-Guid: 0
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" Guid="{0ead09bd-2157-539a-8d6d-c87f95b64d70}" />
    <EventID>1001</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2023-05-01T13:49:34.9611849Z" />
    <EventRecordID>35540</EventRecordID>
    <Correlation ActivityID="{8861af8d-083e-4e1e-9ece-1877f2095b72}" />
    <Execution ProcessID="3096" ThreadID="27424" />
    <Channel>Application</Channel>
    <Computer>LAPTOP-734P5RIS</Computer>
    <Security UserID="S-1-5-21-1169533734-3294246923-2195338406-1001" />
  </System>
  <EventData>
    <Data Name="Bucket">2044503629279316353</Data>
    <Data Name="BucketType">5</Data>
    <Data Name="EventName">RADAR_PRE_LEAK_64</Data>
    <Data Name="Response">Nicht verfügbar</Data>
    <Data Name="CabId">0</Data>
    <Data Name="P1">PhoneExperienceHost.exe</Data>
    <Data Name="P2">1.23022.140.0</Data>
    <Data Name="P3">10.0.22621.2.0.0</Data>
    <Data Name="P4">
    </Data>
    <Data Name="P5">
    </Data>
    <Data Name="P6">
    </Data>
    <Data Name="P7">
    </Data>
    <Data Name="P8">
    </Data>
    <Data Name="P9">
    </Data>
    <Data Name="P10">
    </Data>
    <Data Name="AttachedFiles">
\\?\C:\Users\Test\AppData\Local\Temp\RDR54DC.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c07db6d1-0327-48db-9036-1a1b7483d601.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.aa0da1b3-171b-46d3-a1fc-a3e93c31bdc0.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e3e3969d-9645-4caa-a0a2-ea4548342e23.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.655a6083-daf1-4c0c-90b2-09e06cbe5004.tmp.xml</Data>
    <Data Name="StorePath">NULL</Data>
    <Data Name="AnalysisSymbol">
    </Data>
    <Data Name="Rechecking">0</Data>
    <Data Name="ReportId">cc09e839-5630-4b47-b2fc-e343e307ce79</Data>
    <Data Name="ReportStatus">268435456</Data>
    <Data Name="HashedBucket">90e1571cefddc9387c5f8937f530c981</Data>
    <Data Name="CabGuid">0</Data>
  </EventData>
</Event>

**Comment by dbuechel** [comment] 2023-05-02 09:23
Thanks for the information @dkummer63. The error report you've provided would indicate that the source of the issue is the PhoneExperienceHost.exe application ("Smartphone-Link" or "Your Phone" app by Microsoft, see https://apps.microsoft.com/store/detail/smartphonelink/9NMPJ99VJBWV). It namely appears that the app causes a memory leak. If your student indeed is using that app, they should either try to update or then uninstall it altogether and check whether the error still appears.

**Comment by dbuechel** [comment] 2023-06-13 14:41
Are there any updates or further questions on this issue? Otherwise we'd need to close it for now.

**Comment by dkummer63** [comment] 2023-06-13 14:50
I am sorry to say, that the student left our school, so I was not able to verify the problem. But thank you for your help.

Von: Damian Büchel ***@***.***>
Datum: Dienstag, 13. Juni 2023 um 16:41
An: SafeExamBrowser/seb-win-refactoring ***@***.***>
Cc: Kummer Daniel, GBSL Lehrer ***@***.***>, Mention ***@***.***>
Betreff: Re: [SafeExamBrowser/seb-win-refactoring] Can't start SEB (Issue #584)

Are there any updates or further questions on this issue? Otherwise we'd need to close it for now.

**Comment by dbuechel** [comment] 2023-06-13 15:00
Thanks for the update. Then I'd suggest to close the issue for now, but please do feel free to reopen it in case new insights emerge.

**Closed by dbuechel** 2023-06-13 15:00 UTC
Labels: information required
