### ISSUE TITLE
SEB Locked screen is non-responsive to mouse or keyboard entry

### ISSUE THREAD

**Issue by nvarghese-rm** [SafeExamBrowser/seb-win-refactoring#305] opened 2021-12-22 22:14 UTC
SEB Locked screen is non-responsive to mouse or keyboard entry

**Steps to reproduce**
Student is using SEB Windows with 3.3 version Safe Exam browser installed
Student closes the device lid while student exam status is "In progress" status.
After certain time student opens the device lid to go back to "In progress" exam.
System displays a RED screen as  SEB LOCKED (screenshot attached)
When student clicks into the white text box area and hits Enter on the keyboard to return to the exam as no exit code is configured in the config file, system does not do anything and page is not responsive.
Even if the student clicks  into the white text box area and clicks Unlock, system does not do anything and page is not responsive.
Student needs to hard shutdown the machine and start the device again to login to the exam.

**Expected Behavior**
When student clicks into the white text box area and hits Enter on the keyboard, the red screen should close and return the student to the exam as no exit code is configured in the config file, or
Even if the student clicks  into the white text box area and clicks Unlock, the red screen should close and return the student to the exam as no exit code is configured in the config file

**Screenshots**
![image](https://user-images.githubusercontent.com/87759879/147160525-54861697-c5ee-4201-a8e1-c4cd3ebc8c05.png)

**Version Information**
 - OS: Edition - Windows 10 Pro, Version - 21H1, Installed on - 7/10/2020, OS build - 19043.1237
 - SEB-Version 3.3.1

**Additional Context**
The issue was **NOT** observed when using
 - OS: Edition - Windows 10 Enterprise Version 20H2, Installed 18/07/2020, OS Build 19042.1348
 - SEB-Version 3.3.1

**Comment by dbuechel** [comment] 2021-12-23 13:49
This was a bug in Windows which we actually reported to MSFT and which should have been fixed. However, if the version information you provide is indeed correct, then I'm afraid that MSFT introduced a regression and the bug is again present in recent Windows versions.

However, you don't need to forcefully shutdown the system, pressing CTRL+ALT+DEL or WIN+L and then cancelling the Security Screen should return you to the SEB session which then should again be receiving user input.

**Comment by nvarghese-rm** [comment] 2022-01-12 20:53
Hi @dbuechel , Are you planning to report this to MSFT ?

**Comment by dbuechel** [comment] 2022-01-13 10:26
Yes, though I will need to try to reproduce it myself first. We're currently however busy with the final work for version 3.3.2, so this won't happen before that release is through.

**Comment by dbuechel** [comment] 2022-01-13 10:29
@nvarghese-rm If you happen to have direct contact to MSFT, then it'd be highly appreciated if you could try to report it in the meantime.

**Comment by dbuechel** [comment] 2022-04-20 10:15
I have to correct myself: I just searched my communication with MSFT from last year and found that the issue was only fixed in an Insider Preview build (specifically 21346 and above). It thus appears that the fix hasn't yet found its way into the public release version(s) of Windows. I have contacted MSFT again and inquired about a potential release timeline for the fix.

Meanwhile, **you don't have to hard shutdown your machine when the issue happens!** Simply press `CTRL+ALT+DEL` or `WIN+L` when the lock screen is not responsive, and then after returning from the Security or Lock Screen of Windows to the active SEB session you should be able to close the SEB lock screen normally.

**Comment by dbuechel** [comment] 2022-04-20 10:20
@nvarghese-rm Have you by chance also investigated whether the issue happens with Windows 11 as well?

**Comment by nvarghese-rm** [comment] 2022-04-20 21:08
@dbuechel - Our client advised us in February that on applying the latest Windows updates on the Windows 10 device, the issue was fixed. Sorry for not advising you earlier. Thanks

**Comment by dbuechel** [comment] 2022-04-21 06:58
Thanks for the update, @nvarghese-rm. If you have the information, would you mind sharing the exact Windows 10 version and build information where the issue appears to be fixed?

**Comment by dbuechel** [comment] 2022-04-26 15:22
I have received word from Microsoft, it appears that they had to revert that fix from the Insider builds because it introduced some regressions for other scenarios. MSFT promised to keep us updated regarding further information about a possible release timeline. In the meantime, we'll thus have to mark this as "can't fix".

IMPORTANT: Please read https://github.com/SafeExamBrowser/seb-win-refactoring/issues/305#issuecomment-1103762410 regarding a workaround if you encounter this issue!

**Comment by dbuechel** [comment] 2022-04-27 09:35
I have received another update: The fix is already deployed in Windows 11, whether the fix will be re-deployed to systems running Windows 10 remains to be seen.

**Closed** 2022-06-14 13:35 UTC
Labels: won't fix, system bug

**Comment by JanSommen** [comment] 2023-12-19 08:21
I had the same problem with SEB version 3.6.0 and win10 Edu 20H2 build 19042.1466
