### ISSUE TITLE
IndexedDB Open Very Slow

### ISSUE THREAD

**Issue by keean** [SafeExamBrowser/seb-win-refactoring#36] opened 2020-10-24 08:15 UTC
Our application runs fast in Chrome, Firefox, Safari, Edge (chrome engine), and SEB-2, on multiple different platforms (Windows 10, MacOS-X, iOS, Linux, Android). In SEB-3 (on up to date Windows 10) it starts running okay, but occasionally has very long pauses (3+ seconds) when changing questions or loading images. As you can imagine this is not acceptable in an exam. Using remote logging I have traced the problem to the indexeddb 'open' call. After a few calls to open which run fast, it will cause a long block. The sometimes seems to be as often as every other call, but at other times it can be as few as one in ten. The DB workload is a mix of reads and writes, with generally the reads being large and the writes being small.

Does SEB do something different around the IndexedDB open than Chrome or Firefox? The open source 'chromium' browser is also fast and has no problems?

Any ideas what could be causing this? I am happy to provide debugging info if that helps.

**Comment by keean** [comment] 2020-10-27 08:51
I am not sure what is going on here, but the delete and clear database commands are much slower than SEB2 as well.

**Comment by danschlet** [comment] 2020-10-28 14:57
SEB 3.0 just uses the CEF3 (Chromium Embed Framework) as browser engine and doesn't change anything regarding IndexedDB. The Chromium version in SEB 3.0.1 is 81.0.4044.138 (see release notes), which isn't the latest Chromium version, don't know if that version had some issues with IndexedDB. SEB 3.1 uses a newer Chromium version, you can check out the latest beta build to see if it works better. I don't know if you could find out more about the issue by using developer tools in the browser (which you can activate in SEB 3).

If it's not fixed in with a newer CEF version, then probably they have some issue with IndexedD and we couldn't do much about it. But at some point we will change the browser engine to Microsofts Chromium based new WebView2 (if it works as well as they promise), which should be available end of the year for .NET.

**Comment by keean** [comment] 2020-10-28 15:40
There is definitely something different... To delete 5 objectStores takes under one second in Chrome (86.0.4240.111):

[155.42666499997722,"DELETE_EXAM_DATA"]
[155.62365999998292,"DELETE_TIME 0.1957599999732338"]

Yet takes over 28 seconds in SEB-3!

 [22.678790000034496,"DELETE_EXAM_DATA"]
[51.098210000025574,"DELETE_TIME 28.418174999998882"]

That's not a small difference! Are you somehow forcing a commit? I know that Chrome completes the transaction as soon as the operating system has the command, (IE the program could terminate, but the delete would still happen) rather than waiting for it to commit to disk (IE pulling the power plug on the OS would you might see a partial delete).

**Comment by keean** [comment] 2020-10-28 16:06
I have got the old build of Chromium (81.0.4404.0) and this also take a long time to delete:

[56.29417499998817,"DELETE_EXAM_DATA"]
[85.59071000001859,"DELETE_TIME 29.29527499998221"]

So it looks like it is a Chromium version issue. How can I download a build of SEB-3.1 to test? What version of Chromium is 3.1 using?

**Comment by danschlet** [comment] 2020-10-28 22:19
1. Go to the Code tab of this repository
2. Scroll down, you'll see the link to [Release Builds](https://sebdev-let.ethz.ch/project/appveyor/seb-win-refactoring)
3. Click on "Platform: x86"
4. Click on "Artifacts"
5. Download and use the exe setup bundle

I don't know the version (our Windows developer might answer that later).

**Comment by keean** [comment] 2020-10-30 10:05
SEB 3.1 (x64) is a lot faster, taking only 3 seconds to delete the data, compared to nearly 30 seconds on the 3.0.x version, a 10x speed up. However it is still significantly slower than the current version of Chrome which as you can see above took only 0.2 seconds, which is a another 10x - 15x faster again.

If I knew the version of Chromium it was based on, I could test and confirm if this problem with Chromium, and whether this would be resolves in future SEB versions, as they will use newer versions of Chromium as a starting point.

**Comment by danschlet** [comment] 2020-10-30 13:23
Our Windows developer cannot answer right now, but I guess it's version Chromium 85.0.4183.121 (CefSharp v85.3.130).
Check out the repository of CefSharp https://github.com/cefsharp/CefSharp/releases, there you see currently available builds, release notes and known issues. When you have problems with the SEB 3.x browser engine, I would search issues in this repository, maybe it was already discussed there.

**Comment by dbuechel** [comment] 2020-11-04 20:08
You can check the version of the used engine by entering `chrome://version` in the address bar. For SEB 3.1, it is currently 85.0.4183.121.

**Comment by dbuechel** [comment] 2020-11-04 20:10
With respect to your issue report, as @danschlet already mentioned, we don't do anything with or for IndexedDB. You'd need to use the developer tools within SEB and see whether you can find the root cause, it might well be an issue in CEF or Chromium itself.

**Comment by dbuechel** [comment] 2020-11-05 15:40
I'll close this for now. Feel free to re-open the issue when you need further help or information.

**Closed by dbuechel** 2020-11-05 15:40 UTC
