### ISSUE TITLE
text to speech

### ISSUE THREAD

**Issue by Kris-lucas** [SafeExamBrowser/seb-win-refactoring#827] opened 2024-03-12 14:27 UTC
> [!IMPORTANT]
> - Please _always_ consult the documentation first before creating a bug report: https://safeexambrowser.org/windows/win_usermanual_en.html.
> - Please _always_ attach the log file(s) of the affected session(s)! They can be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Describe the Bug**

Hi there i am working forn the ICT department of a school and we founded a problem with text to speech.
We were using bookwidgets for the test and seb for the security.
In bookwidget we activate text to speech but when we do the test with the students 50% of that class don't work.
The problem is that when they select the part it has to read it says "no vocal:english_gb" or something like that.

I looked it up on the site of bookwidget and found out that feature is dependend of the features of the browser.
can you help us?

KInd Regards

**Version Information**
 - OS: [e.g. Windows 10 Professional, Version 1803]
 - SEB-Version [e.g. SEB 3.0.1]

**Additional Context**

**Comment by dbuechel** [comment] 2024-03-13 08:54
I doubt this is an issue in SEB itself, otherwise it would not work for all students. Either way, we'd need a clear and concise list of step-by-step instructions on how to reliably reproduce the issue, otherwise there's not much we can do about it.

**Comment by xavier-bw** [comment] 2024-03-13 09:31
Assuming this is Windows, can it be that no text to speech voice for English is not installed in Windows itself?  I have the impression these voices are used from Safe Exam Browser.

**Comment by dbuechel** [comment] 2024-03-13 09:56
@xavier-bw Thanks for the input, that might indeed also be the cause of the issue.

**Comment by Kris-lucas** [comment] 2024-03-13 10:05
hi there where can you check it? if it is installed?

**Comment by xavier-bw** [comment] 2024-03-13 10:10
https://support.microsoft.com/en-gb/topic/download-languages-and-voices-for-immersive-reader-read-mode-and-read-aloud-4c83a8d8-7486-42f7-8e46-2b0fdf753130

**Comment by dbuechel** [comment] 2024-03-13 10:39
Excellent, then I presume we can close the issue for the time being.

**Closed by dbuechel** 2024-03-13 10:39 UTC
Labels: information required, can't reproduce
