### ISSUE TITLE
SEB failed session please cek log fiels

### ISSUE THREAD

**Issue by BlingVortexz** [SafeExamBrowser/seb-win-refactoring#794] opened 2024-01-31 13:21 UTC
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**
i cant go in seb it says failed to create session

**Steps to Reproduce**
1. Go to 'windows '
2. Click on 'safe exam'
3. See error

**Expected Behavior**

**Screenshots**

**Version Information**
 - OS: [e.g. Windows 10 Professional, Version [`1803]`](
![sebfail](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/158293285/fede81ee-d9a4-4308-a7bf-39d84de20ec2)
)
 - SEB-Version latest seb version

**Additional Context**

**Comment by BlingVortexz** [comment] 2024-01-31 13:22
oh and my laptop is wiindows 11

**Comment by BlingVortexz** [comment] 2024-01-31 13:24
i already tried everything uninstall install using c++ uninstall seb c++  install it again still cannot

**Comment by dbuechel** [comment] 2024-01-31 14:11
Please provide the log file(s) of the affected session, they can be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Comment by BlingVortexz** [comment] 2024-02-01 00:40
[1400-10-08_10h55m19s_Client (1).log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/14118863/1400-10-08_10h55m19s_Client.1.log)
here

**Comment by dbuechel** [comment] 2024-02-02 09:21
There appears to be an issue with a culture / input language you've configured on your system:

1400-10-08 10:55:20.956 [01] - ERROR: Caught unexpected exception while performing operation 'LazyInitializationOperation'!

```
   Exception Message: Culture is not supported. Parameter name: culture 4096 (0x1000) is an invalid culture identifier.
   Exception Type: System.Globalization.CultureNotFoundException

   at System.Globalization.CultureInfo.InitializeFromCultureId(Int32 culture, Boolean useUserOverride)
   at System.Windows.Input.InputProcessorProfiles.get_InputLanguageList()
   at SafeExamBrowser.SystemComponents.Keyboard.Keyboard.Initialize() in C:\Users\appveyor\projects\seb-win-refactoring\SafeExamBrowser.SystemComponents\Keyboard\Keyboard.cs:line 54
   at SafeExamBrowser.Client.Operations.ShellOperation.InitializeSystemComponents() in C:\Users\appveyor\projects\seb-win-refactoring\SafeExamBrowser.Client\Operations\ShellOperation.cs:line 207
   at SafeExamBrowser.Client.Operations.ShellOperation.Perform() in C:\Users\appveyor\projects\seb-win-refactoring\SafeExamBrowser.Client\Operations\ShellOperation.cs:line 81
   at SafeExamBrowser.Core.OperationModel.OperationSequence.Perform() in C:\Users\appveyor\projects\seb-win-refactoring\SafeExamBrowser.Core\OperationModel\OperationSequence.cs:line 108
```

Could you please share exactly which cultures / input languages you've configured on your system (best with a screens shot)?

**Comment by BlingVortexz** [comment] 2024-02-03 14:01
this?
![language](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/158293285/5cc4d3b5-8d86-424c-a5cd-ccb84a88b93b)

**Comment by dbuechel** [comment] 2024-02-06 14:06
Could you please one by one deactivate resp. remove each the three languages you've installed in order to identify which appears to be causing the problem?

**Comment by BlingVortexz** [comment] 2024-02-07 02:40
i delete 3 of them still cant

**Comment by dbuechel** [comment] 2024-02-07 09:35
Okay, that is weird and unexpected. But it might have something to do with the warning you have there saying "Your Windows license only supports one display language". Did you restart your system after removing the languages?

**Comment by BlingVortexz** [comment] 2024-02-08 23:30
oh i didnt restart

**Comment by dbuechel** [comment] 2024-02-09 09:39
So were you able to identify the language causing the issue or even resolve the problem?

**Comment by BlingVortexz** [comment] 2024-02-15 00:02
nope i still cant

**Comment by dbuechel** [comment] 2024-02-22 10:36
Again, I would assume that might be due to the license as mentioned above. Apart from that, we'd need a reliable way to reproduce the issue, otherwise we cannot do anything about it unfortunately.

**Comment by BlingVortexz** [comment] 2024-03-22 01:34
oh i already reseted my windows, now it says i need to configure seb? sorry for not updating

**Comment by BlingVortexz** [comment] 2024-03-24 13:34
![seb](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/158293285/bb381df1-7051-4023-bb56-f0c605ac72eb)

**Comment by dbuechel** [comment] 2024-03-26 11:43
> oh i already reseted my windows, now it says i need to configure seb? sorry for not updating

That would be good news, since that is the default page SEB loads if you don't specify a particular (exam) configuration.

**Comment by BlingVortexz** [comment] 2024-03-27 00:04
ohh so i need to input a exam key first?

**Comment by dbuechel** [comment] 2024-03-27 09:37
You'll need to use the exam configuration or link provided by your institution, exactly.

**Comment by BlingVortexz** [comment] 2024-03-28 05:59
im sorry i dont understand can u give me an example?

**Comment by dbuechel** [comment] 2024-03-28 08:48
Please explain what you're trying to achieve now that SEB appears to work normally: Do you need to perform an exam? Then your institution needs to provide you with instructions on how to do so.

**Comment by fauzibadr** [comment] 2024-04-24 11:11
guys i have the same problem, can you guys help me with this?
![Screenshot (35)](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/167983494/5e13fe71-93a3-4a10-85f9-e4960144901e)

**Comment by dbuechel** [comment] 2024-04-24 13:21
@fauzibadr Please check and/or post the log file specified in the error message.

**Comment by Vlpg** [comment] 2024-04-24 18:42
Hello, I have the same problem and here's what in my log file. Thank you.

```
2024-04-24 23:38:10.980 [01] - ERROR: Caught unexpected exception while performing operation 'LazyInitializationOperation'!

   Exception Message: A procedure imported by 'CefSharp.Core.Runtime.dll' could not be loaded.
   Exception Type: System.IO.FileLoadException

   at CefSharp.CefSettingsBase..ctor()
   at SafeExamBrowser.Browser.BrowserApplication.InitializeCefSettings() in C:\Users\appveyor\projects\seb-win-refactoring-2cm5n6dku3tpmv82\SafeExamBrowser.Browser\BrowserApplication.cs:line 332
   at SafeExamBrowser.Browser.BrowserApplication.Initialize() in C:\Users\appveyor\projects\seb-win-refactoring-2cm5n6dku3tpmv82\SafeExamBrowser.Browser\BrowserApplication.cs:line 112
   at SafeExamBrowser.Client.Operations.BrowserOperation.Perform() in C:\Users\appveyor\projects\seb-win-refactoring-2cm5n6dku3tpmv82\SafeExamBrowser.Client\Operations\BrowserOperation.cs:line 47
   at SafeExamBrowser.Core.OperationModel.OperationSequence.Perform() in C:\Users\appveyor\projects\seb-win-refactoring-2cm5n6dku3tpmv82\SafeExamBrowser.Core\OperationModel\OperationSequence.cs:line 108

```

**Comment by fauzibadr** [comment] 2024-04-25 02:10
2024-04-25_09h09m43s_Runtime.log like this?

**Comment by fauzibadr** [comment] 2024-04-25 02:12
I'm indonesian so sorry guys if I can't understand english well

**Comment by fauzibadr** [comment] 2024-04-25 02:16
/* Safe Exam Browser, Version 3.7.0 (x64), Build 3.7.0.682
/* Copyright © 2024 ETH Zürich, IT Services
/* 
/* Please visit https://www.github.com/SafeExamBrowser for more information.

# Application started at 2024-04-25 09:09:43.216
# Running on Windows 10, Microsoft Windows NT 10.0.19045.0 (x64)
# Computer 'DESKTOP-5UICM59' is a 103C_5335KV G=N L=CON B=HP               HP Notebook manufactured by HP
# Runtime-ID: fe638c70-701f-4810-932a-53397c5e5b4f

2024-04-25 09:09:44.716 [07] - INFO: Initiating startup procedure...
2024-04-25 09:09:44.845 [07] - INFO: Loading text data...
2024-04-25 09:09:44.849 [07] - DEBUG: [Text] System language is 'en', trying to load data...
2024-04-25 09:09:44.866 [07] - DEBUG: [Text] Data successfully loaded.
2024-04-25 09:09:44.868 [07] - INFO: Starting communication host...
2024-04-25 09:09:44.924 [09] - DEBUG: [RuntimeHost] Communication host is opening...
2024-04-25 09:09:44.988 [09] - DEBUG: [RuntimeHost] Communication host has been opened.
2024-04-25 09:09:44.988 [09] - DEBUG: [RuntimeHost] Successfully started communication host for endpoint 'net.pipe://localhost/safeexambrowser/runtime/73c7d0a0-6803-468e-ad3b-1daca164eab9'.
2024-04-25 09:09:44.990 [07] - INFO: Attempting to verify application integrity...
2024-04-25 09:09:45.241 [07] - INFO: Application integrity successfully verified.
2024-04-25 09:09:45.245 [07] - INFO: Application successfully initialized.

2024-04-25 09:09:45.301 [07] - INFO: ### ------------------------------------ Session Start Procedure ------------------------------------- ###
2024-04-25 09:09:45.309 [07] - INFO: Initializing new session configuration...
2024-04-25 09:09:45.312 [07] - INFO:  -> Client-ID: 067fd1c2-a496-41bd-8764-10c9d5874b5a
2024-04-25 09:09:45.315 [07] - INFO:  -> Runtime-ID: fe638c70-701f-4810-932a-53397c5e5b4f
2024-04-25 09:09:45.331 [07] - INFO:  -> Session-ID: c5ad33b5-e0c3-4005-a80e-98cb873265af
2024-04-25 09:09:45.331 [07] - INFO: Initializing application configuration...
2024-04-25 09:09:45.331 [07] - INFO: Found configuration file in app data directory: 'file:///C:/Users/FAUZI/AppData/Roaming/SafeExamBrowser/SebClientSettings.seb'.
2024-04-25 09:09:45.363 [07] - INFO: [ConfigurationRepository] Initialized default settings, now attempting to load 'file:///C:/Users/FAUZI/AppData/Roaming/SafeExamBrowser/SebClientSettings.seb'...
2024-04-25 09:09:45.378 [07] - DEBUG: [FileResourceLoader] Can load 'file:///C:/Users/FAUZI/AppData/Roaming/SafeExamBrowser/SebClientSettings.seb' as it is an existing file.
2024-04-25 09:09:45.378 [07] - DEBUG: [FileResourceLoader] Loading data from 'file:///C:/Users/FAUZI/AppData/Roaming/SafeExamBrowser/SebClientSettings.seb'...
2024-04-25 09:09:45.378 [07] - DEBUG: [FileResourceLoader] Created 'System.IO.FileStream' for 3.597 KB data in 'file:///C:/Users/FAUZI/AppData/Roaming/SafeExamBrowser/SebClientSettings.seb'.
2024-04-25 09:09:45.378 [07] - INFO: [ConfigurationRepository] Tried to load data from 'file:///C:/Users/FAUZI/AppData/Roaming/SafeExamBrowser/SebClientSettings.seb' using FileResourceLoader -> Result: Success.
2024-04-25 09:09:45.378 [07] - DEBUG: [BinaryParser] 'System.IO.FileStream' starting with 'pwcc' matches the Binary format.
2024-04-25 09:09:45.394 [07] - DEBUG: [GZipCompressor] Starting decompression of 'System.IO.FileStream' with 3.597 KB data...
2024-04-25 09:09:45.394 [07] - DEBUG: [GZipCompressor] Successfully decompressed 3.597 KB to 3.574 KB data.
2024-04-25 09:09:45.394 [07] - DEBUG: [BinaryParser] Attempting to parse password block with prefix 'pwcc'...
2024-04-25 09:09:45.394 [07] - DEBUG: [PasswordEncryption] Parsing encryption header...
2024-04-25 09:09:45.394 [07] - DEBUG: [PasswordEncryption] Generating keys for authentication and decryption...
2024-04-25 09:09:45.706 [07] - DEBUG: [PasswordEncryption] Generating HMACs for authentication...
2024-04-25 09:09:45.706 [07] - DEBUG: [PasswordEncryption] Decrypting data...
2024-04-25 09:09:45.706 [07] - DEBUG: [GZipCompressor] Starting decompression of 'System.IO.MemoryStream' with 3.5 KB data...
2024-04-25 09:09:45.706 [07] - DEBUG: [GZipCompressor] Successfully decompressed 3.5 KB to 41.017 KB data.
2024-04-25 09:09:45.706 [07] - DEBUG: [BinaryParser] Attempting to parse plain data block...
2024-04-25 09:09:45.706 [07] - DEBUG: [XmlParser] Found root node, starting to parse data...
2024-04-25 09:09:45.722 [07] - DEBUG: [XmlParser] Finished parsing -> Result: Success.
2024-04-25 09:09:45.722 [07] - INFO: [ConfigurationRepository] Tried to parse data from 'System.IO.FileStream' using BinaryParser -> Result: Success.
2024-04-25 09:09:45.800 [07] - INFO: The configuration was successful.
2024-04-25 09:09:45.816 [07] - INFO: Validating version restrictions...
2024-04-25 09:09:45.816 [07] - INFO: There are no version restrictions for the configuration.
2024-04-25 09:09:45.816 [07] - INFO: Validating remote session policy...
2024-04-25 09:09:45.816 [07] - DEBUG: [RemoteSessionDetector] System appears not to be running in a remote session.
2024-04-25 09:09:45.831 [07] - INFO: Attempting to verify cursor configuration...
2024-04-25 09:09:45.831 [07] - WARNING: Configuration of cursor 'Arrow' is compromised: 'C:\Users\FAUZI\Downloads\FILE SAYA\PANAH\flaming sword.cur'!
2024-04-25 09:09:45.831 [07] - WARNING: Failed to verify cursor configuration or configuration is compromised! Aborting session initialization...
2024-04-25 09:09:45.831 [07] - INFO: Attempting to verify ease of access configuration...
2024-04-25 09:09:45.831 [07] - INFO: Ease of access configuration successfully verified (value does not exist).
2024-04-25 09:09:45.847 [07] - INFO: ### -------------------------------------- Session Start Failed -------------------------------------- ###

2024-04-25 09:10:19.367 [06] - INFO: Initiating shutdown procedure...
2024-04-25 09:10:19.369 [06] - INFO: Stopping communication host...
2024-04-25 09:10:19.372 [06] - DEBUG: [RuntimeHost] Communication host is closing...
2024-04-25 09:10:19.389 [06] - DEBUG: [RuntimeHost] Communication host has been closed.
2024-04-25 09:10:19.389 [06] - DEBUG: [RuntimeHost] Terminated communication host for endpoint 'net.pipe://localhost/safeexambrowser/runtime/73c7d0a0-6803-468e-ad3b-1daca164eab9'.
2024-04-25 09:10:19.390 [06] - INFO: Application successfully finalized.

# Application terminated at 2024-04-25 09:10:19.448

**Comment by fauzibadr** [comment] 2024-04-25 02:33
I know my problem now, I open the log file and I see the app won't open just because my custom cursor folder, for some reason it make the app not started, so I change the cursor to default setting and it worked normally. LOL

**Comment by ricosa7** [comment] 2024-04-25 11:55
Hello i have a problem in SEB App, could you help me?
[2024-04-25_19h54m52s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/15109220/2024-04-25_19h54m52s_Client.log)
![SEB](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/168091753/1bab3134-7c7a-47c8-a0d4-ccebf5369a27)

[2024-04-25_19h54m52s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/15109221/2024-04-25_19h54m52s_Runtime.log)

**Comment by dbuechel** [comment] 2024-04-25 13:14
> Hello i have a problem in SEB App, could you help me? [2024-04-25_19h54m52s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/15109220/2024-04-25_19h54m52s_Client.log) ![SEB](https://private-user-images.githubusercontent.com/168091753/325594908-1bab3134-7c7a-47c8-a0d4-ccebf5369a27.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTA5NTksIm5iZiI6MTcxNDA1MDY1OSwicGF0aCI6Ii8xNjgwOTE3NTMvMzI1NTk0OTA4LTFiYWIzMTM0LTdjN2EtNDdjOC1hMGQ0LWNjZWJmNTM2OWEyNy5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxMzEwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2VjYmIwMjJmYmE2YmRjM2U5ZTFlNmIzOWFmNzIxMDRkMzhjYTY3YWRjYjI1ZjU4MTBkYTEzYzUxOWQyMjA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DGAQrpVfYQhcjY75ov6eNWVd1wW7D_5vhqxZg4lE6vA)
> 
> [2024-04-25_19h54m52s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/15109221/2024-04-25_19h54m52s_Runtime.log)
> 
> By the way these are the app that i installed and i installed net framework 4.8 too. ![App](https://private-user-images.githubusercontent.com/168091753/325595760-9cd2dead-83af-4faa-a140-bcfad0fe8f02.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTA5NTksIm5iZiI6MTcxNDA1MDY1OSwicGF0aCI6Ii8xNjgwOTE3NTMvMzI1NTk1NzYwLTljZDJkZWFkLTgzYWYtNGZhYS1hMTQwLWJjZmFkMGZlOGYwMi5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxMzEwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTA0NzQ0OTc1YjEyYmEzNDYyNTBjY2NmNTE0ZGQ5ZTU4NzhmODk0Nzk0ZmQ5MjE1ZmU5OGEwYWEyN2VjN2IzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OuXbz9hKCNgfuB_SEKXgL5RdlkVrvDl4hdRRNucQl3Y)
> 
> Thanks before.

Dito.

**Closed** 2024-04-25 13:21 UTC
Labels: information required, can't reproduce

**Comment by ricosa7** [comment] 2024-04-25 13:25
> > Hello i have a problem in SEB App, could you help me? [2024-04-25_19h54m52s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/15109220/2024-04-25_19h54m52s_Client.log) ![SEB](https://private-user-images.githubusercontent.com/168091753/325594908-1bab3134-7c7a-47c8-a0d4-ccebf5369a27.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTA5NTksIm5iZiI6MTcxNDA1MDY1OSwicGF0aCI6Ii8xNjgwOTE3NTMvMzI1NTk0OTA4LTFiYWIzMTM0LTdjN2EtNDdjOC1hMGQ0LWNjZWJmNTM2OWEyNy5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxMzEwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2VjYmIwMjJmYmE2YmRjM2U5ZTFlNmIzOWFmNzIxMDRkMzhjYTY3YWRjYjI1ZjU4MTBkYTEzYzUxOWQyMjA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DGAQrpVfYQhcjY75ov6eNWVd1wW7D_5vhqxZg4lE6vA)
> > [2024-04-25_19h54m52s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/15109221/2024-04-25_19h54m52s_Runtime.log)
> > By the way these are the app that i installed and i installed net framework 4.8 too. ![App](https://private-user-images.githubusercontent.com/168091753/325595760-9cd2dead-83af-4faa-a140-bcfad0fe8f02.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNTA5NTksIm5iZiI6MTcxNDA1MDY1OSwicGF0aCI6Ii8xNjgwOTE3NTMvMzI1NTk1NzYwLTljZDJkZWFkLTgzYWYtNGZhYS1hMTQwLWJjZmFkMGZlOGYwMi5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxMzEwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTA0NzQ0OTc1YjEyYmEzNDYyNTBjY2NmNTE0ZGQ5ZTU4NzhmODk0Nzk0ZmQ5MjE1ZmU5OGEwYWEyN2VjN2IzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OuXbz9hKCNgfuB_SEKXgL5RdlkVrvDl4hdRRNucQl3Y)
> > Thanks before.
> 
> Dito.

Hello, i already installed the visual C++ redistributable 2015-2022. But the problem is still.

**Comment by dbuechel** [comment] 2024-04-25 13:47
Make sure you're using the setup bundle (.exe) to install SEB, as is explained prominently in the release notes.

**Comment by ricosa7** [comment] 2024-04-25 13:57
yes, i,m using setup bundle. i download from this link https://sourceforge.net/projects/seb/files/seb/SEB_3.7.0/SEB_3.7.0.682_SetupBundle.exe/download?use_mirror=nchc&failedmirror=zenlayer%7Czenlayer.dl.sourceforge.net

**Comment by dbuechel** [comment] 2024-04-25 14:01
Yes, try to uninstall all, restart your computer and try to install SEB again (using the setup bundle).

**Comment by ricosa7** [comment] 2024-04-25 14:38
Hello, i already restart my pc, uninstall them, but the problem is still.

**Comment by dbuechel** [comment] 2024-04-25 15:24
See https://github.com/cefsharp/CefSharp/discussions/4336.

**Comment by ricosa7** [comment] 2024-04-25 15:26
Okay. I'll try again in another pc tomorrow.

**Comment by ricosa7** [comment] 2024-04-26 04:21
Hello Damian, i installed on windows 10, just to make sure. Does this app run correctly? Then, i only need to click my exam link, right?
![20240426_121652](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/168091753/7dc3094e-1dfa-4b5d-a8f0-7ee2ec668ca8)

**Comment by ricosa7** [comment] 2024-04-26 15:06
Thanks for the advice.

**Comment by BlingVortexz** [comment] 2024-04-30 06:16
hey i think i know the source of problem , everytime i forgot to submit exam, i just closed my laptop when i open laptop , it suddenly says cek log error ,crashed and something like that.

**Comment by BlingVortexz** [comment] 2024-04-30 06:16
i just got the thing again

**Comment by dbuechel** [comment] 2024-04-30 15:51
@BlingVortexz SEB is not intended to remain running whilst going into standby or power saving mode, so this indeed may be an issue.
