### ISSUE TITLE
SEB quits unexpectedly

### ISSUE THREAD

**Issue by acamacho-unige** [SafeExamBrowser/seb-win-refactoring#522] opened 2022-11-23 15:05 UTC
**Describe the Bug**
We are currently having an unusual amount of crashes with the version 3.4.0 of Safe Exam Browser.
What we saw was mostly happening when opening multiple additional browser windows with an application (but not on every case).

**Steps to Reproduce**
Create an exam on moodle, upload a SEB config file, and do the exam.
While doing the exam, something makes SEB crash and quit without any warning or security.

We couldn't find in logs something useful to understand the problem.

**Expected Behavior**
SEB not to quit unexpectedly.

**Version Information**
 - OS: Windows 10, Version 1803
 - SEB-Version: 3.4.0

_Logs have been sent privately._

**Comment by dbuechel** [comment] 2022-11-24 08:38
Thanks for your report, we'll have a look at the issue.

**Comment by Anajrim01** [comment] 2022-11-30 12:19
Maybe this can be of use, the same thing happened to me during my test. Restarted the test and it all worked fine thereafter.
```
2022-11-30 10:21:41.660 [01] - INFO: Initiating shutdown procedure...
2022-11-30 10:21:41.730 [01] - INFO: Emptying clipboard...
2022-11-30 10:21:41.734 [01] - INFO: Terminating browser...
2022-11-30 10:21:41.739 [01] - INFO: [BrowserApplication] Initiating termination...
2022-11-30 10:21:42.096 [21] - ERROR: [RuntimeProxy] Failed to ping host!

   Exception Message: Ett fel inträffade under skrivning till pipe. Denna pipe håller på att stängas. (232, 0xe8).
   Exception Type: System.ServiceModel.CommunicationException


Server stack trace: 
   vid System.ServiceModel.Channels.StreamConnection.Write(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout)
   vid System.ServiceModel.Channels.StreamConnection.Write(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout, BufferManager bufferManager)
   vid System.ServiceModel.Channels.FramingDuplexSessionChannel.OnSendCore(Message message, TimeSpan timeout)
   vid System.ServiceModel.Channels.TransportDuplexSessionChannel.OnSend(Message message, TimeSpan timeout)
   vid System.ServiceModel.Channels.OutputChannel.Send(Message message, TimeSpan timeout)
   vid System.ServiceModel.Dispatcher.DuplexChannelBinder.Request(Message message, TimeSpan timeout)
   vid System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   vid System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   vid System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   vid System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   vid System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   vid SafeExamBrowser.Communication.Contracts.ICommunication.Send(Message message)
   vid SafeExamBrowser.Communication.Proxies.BaseProxy.Send(Message message) i C:\Users\appveyor\projects\seb-win-refactoring-4w22kouryjnrjj4t\SafeExamBrowser.Communication\Proxies\BaseProxy.cs:rad 132
   vid SafeExamBrowser.Communication.Proxies.BaseProxy.TestConnection() i C:\Users\appveyor\projects\seb-win-refactoring-4w22kouryjnrjj4t\SafeExamBrowser.Communication\Proxies\BaseProxy.cs:rad 163

   Inner Exception Message: Skrivåtgärden misslyckades. Se det inre undantaget.
   Inner Exception Type: System.IO.IOException

   vid System.Net.Security.NegotiateStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   vid System.Net.Security.NegotiateStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   vid System.ServiceModel.Channels.StreamConnection.Write(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout)

   Inner Exception Message: Ett fel inträffade under skrivning till pipe. Denna pipe håller på att stängas. (232, 0xe8).
   Inner Exception Type: System.ServiceModel.CommunicationException

   vid System.ServiceModel.Channels.PipeConnection.WriteHelper(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout, Object& holder)
   vid System.ServiceModel.Channels.PipeConnection.Write(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout)
   vid System.ServiceModel.Channels.BufferedConnection.WriteNow(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout, BufferManager bufferManager)
   vid System.ServiceModel.Channels.BufferedConnection.Write(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout)
   vid System.ServiceModel.Channels.ConnectionStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   vid System.Net.Security.NegotiateStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   vid System.Net.Security.NegotiateStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)

   Inner Exception Message: Ett fel inträffade under skrivning till pipe. Denna pipe håller på att stängas. (232, 0xe8).
   Inner Exception Type: System.IO.PipeException

   vid System.ServiceModel.Channels.PipeConnection.StartSyncWrite(Byte[] buffer, Int32 offset, Int32 size, Object& holder)
   vid System.ServiceModel.Channels.PipeConnection.WriteHelper(Byte[] buffer, Int32 offset, Int32 size, Boolean immediate, TimeSpan timeout, Object& holder)
```

**Comment by dbuechel** [comment] 2022-12-19 13:00
As mentioned via e-mail, I'd need the information from the Windows event log in order to determine the actual cause of failure. @acamacho-unige Were you able to retrieve these in the meantime?

**Comment by moehzhaw** [comment] 2022-12-19 13:13
Hi

We have some issues within the following setting. This may be comparable with this discussion here, especially the manager's problem (see 2) below).

Our setting:

- We run exams with BYOD.
- We're on on Moodle 3.11.
- The students start the SEB with an Config-File.
- The students have to do two Moodle-tests (MC-question-types, drag-and-drop and open questions (some of them with short answers). 
- The second test can't be opend, unless the first test is handed in (restriction based upon activity completion).
- The teacher has already worked in this setting several times within several years and had the following problem (see 1) below) for the first time... 

We have problems as follows:
1) Students in an exam-setting (some of them with HP Core i7 zBook ): Problem on Windows with SEB-Version 3.4.0: It is not possible to fill in the second test. (The first tests worked out well. But then with the second test, the students have access to the test but, they can't give any answers.) The students changed the device and then it worked out well. (About 5-10% of the students had this problem. The rest of the students were all fine.)
2) Manager (doing some review-tests with DELL Latitude 7420): Problem on Windows 10 Enterprise with SEB-Version 3.4.1: The second test crashed either a) during giving answers or b) while handing in. This results in the SEB finishing automaticly (without exit-password). It is possible to restart the exam and catch up at the point when the system crashed. Finishing the test and handing it in for a second time worked out without error. (The manager did 4 review-tests and had each problem twice...)

= Do we know these issues already?
= Are these issues comparable with the discussion here? Or is it anything else?
= Do we know a solution for these issues?

Best regards, Marcel

**Comment by dbuechel** [comment] 2022-12-19 15:10
@moehzhaw The second point may be related to this issue, but there we'd need to have the actual event log entry in the application log from the Windows event viewer as well in order to be able to further investigate the problem. For the other aspects mentioned in your comment, please move them to a new issue as they are unrelated to this issue.

**Comment by udasch** [comment] 2022-12-22 20:22
We have a similar problem: we allow a website in our test. It’s opened in a new popup. Inside that website there’s a link to a PDF file that opens in a second popup window. Closing one of the popups crashes the SEB.

The two entries in windows event log are the following. I hope it helps to fix the problem. If you need any more information please let me know. Thanks a lot!

Protokollname: Application
Quelle:        .NET Runtime
Datum:         22.12.2022 21:09:49
Ereignis-ID:   1026
Aufgabenkategorie:Keine
Ebene:         Fehler
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      
Beschreibung:
Anwendung: SafeExamBrowser.Client.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.ObjectDisposedException
   bei System.Windows.Forms.Control.MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)
   bei System.Windows.Forms.Control.Invoke(System.Delegate, System.Object[])
   bei CefSharp.WinForms.Handler.LifeSpanHandler.DoClose(CefSharp.IWebBrowser, CefSharp.IBrowser)
   bei <Module>.CefSharp.Internals.ClientAdapter.DoClose(CefSharp.Internals.ClientAdapter*, scoped_refptr<CefBrowser>*)


Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-12-22T20:09:49.4942478Z" />
    <EventRecordID>49143</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer></Computer>
    <Security />
  </System>
  <EventData>
    <Data>Anwendung: SafeExamBrowser.Client.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.ObjectDisposedException
   bei System.Windows.Forms.Control.MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)
   bei System.Windows.Forms.Control.Invoke(System.Delegate, System.Object[])
   bei CefSharp.WinForms.Handler.LifeSpanHandler.DoClose(CefSharp.IWebBrowser, CefSharp.IBrowser)
   bei &lt;Module&gt;.CefSharp.Internals.ClientAdapter.DoClose(CefSharp.Internals.ClientAdapter*, scoped_refptr&lt;CefBrowser&gt;*)

</Data>
  </EventData>
</Event>




Protokollname: Application
Quelle:        Application Error
Datum:         22.12.2022 21:09:50
Ereignis-ID:   1000
Aufgabenkategorie:(100)
Ebene:         Fehler
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:
Beschreibung:
Name der fehlerhaften Anwendung: SafeExamBrowser.Client.exe, Version: 3.4.0.480, Zeitstempel: 0x62ed24c3
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.2364, Zeitstempel: 0x5b7d4d22
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000002cd29
ID des fehlerhaften Prozesses: 0x1c5c
Startzeit der fehlerhaften Anwendung: 0x01d916413487a828
Pfad der fehlerhaften Anwendung: C:\Program Files\SafeExamBrowser\Application\SafeExamBrowser.Client.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: 64d7c7cb-2e6c-4e7c-8d08-a6b154f1e504
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-12-22T20:09:50.5827891Z" />
    <EventRecordID>49144</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer> </Computer>
    <Security />
  </System>
  <EventData>
    <Data>SafeExamBrowser.Client.exe</Data>
    <Data>3.4.0.480</Data>
    <Data>62ed24c3</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.2364</Data>
    <Data>5b7d4d22</Data>
    <Data>e0434352</Data>
    <Data>000000000002cd29</Data>
    <Data>1c5c</Data>
    <Data>01d916413487a828</Data>
    <Data>C:\Program Files\SafeExamBrowser\Application\SafeExamBrowser.Client.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>64d7c7cb-2e6c-4e7c-8d08-a6b154f1e504</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by dbuechel** [comment] 2022-12-22 21:10
> bei CefSharp.WinForms.Handler.LifeSpanHandler.DoClose(CefSharp.IWebBrowser, CefSharp.IBrowser)
> bei .CefSharp.Internals.ClientAdapter.DoClose(CefSharp.Internals.ClientAdapter*, scoped_refptr*)

Hm, this does look like an error in the browser engine or then how we are using the browser engine (it might be that we have an issue with the object disposal of a browser instance).

> If you need any more information please let me know.

Yes, which exact SEB version are you using? If you're not using the latest release version, could you please retest it with that one, as we're almost always updating the browser engine (and an engine update might possibly fix the issue already).

**Comment by udasch** [comment] 2022-12-23 07:53
Thanks for the fast answer! Actually I use the version 3.4.0 - so I'll have to retest this with 3.4.1 (after Christmas ;-)  Thanks again and I'll tell you if it solved our problem as soon as possible!

**Comment by danschlet** [comment] 2023-01-14 01:00
@dbuechel will be able to look into this issue again in February, if it's not fixed in SEB 3.4.1 or the betas of SEB 3.5. Interestingly according to the [release notes](https://safeexambrowser.org/windows/win_release_notes_en.html), a bug sounding like what you're describing was fixed in SEB 3.2:
Fixed crash when navigating via link in PDF.
Maybe it wasn't fixed for all cases or there was a regression due to a change in the browser engine.

**Comment by udasch** [comment] 2023-01-17 07:47
We finally updated the SEB to the latest release version (3.4.1). Unfortunately it did not solve our problem. The error message still is the same.
It looks like it’s more a problem of timing… when we start the test and at first open the PDF > the SEB crashes. When we first navigate in the test, open another link and later the PDF > everything works out well. It‘s reproducible with different websites and links/PDFs.
Do you still have any idea what’s the problem? Thx. Ute

**Comment by danschlet** [comment] 2023-01-17 15:01
Thanks for the feedback. I guess it's an issue in the browser engine, maybe we need to deal differently with links in PDFs. The fix in SEB 3.2 was described as "Attempt to workaround issue with broken link navigation within PDFs.", so I guess at least now it doesn't fully fix the issue (or it was even not directly related to these crashes). More only @dbuechel will be able to find out hopefully.

**Comment by dbuechel** [comment] 2023-02-07 16:41
@udasch Could you please provide a step-by-step instruction on how to reproduce the issue?

**Comment by dbuechel** [comment] 2023-03-07 23:39
We'll most likely need to close this issue with the release of SEB 3.5.0 as we're unable to reproduce it. Should there arise new insights or a reliable way to reproduce the problem, please do feel free to reopen the issue.

**Closed** 2023-03-13 20:50 UTC

**Comment by amaitland** [comment] 2023-04-01 01:29
> Hm, this does look like an error in the browser engine or then how we are using the browser engine (it might be that we have an issue with the object disposal of a browser instance).

There's the potential for an `ObjectDisposedException` when attempting to marshal back onto the `WinForms UI Thread`. The `Control` would have to be `Disposed` between when we check `Disposed` and attempt to marshal onto the `WinForms UI Thread`. So I would expect this to be very hard to reproduce and happen only in a very specific set of circumstances.

Commit https://github.com/cefsharp/CefSharp/commit/a3f7537122ea4da52025e1ef03231855a5a536f7 adds a `try catch` and is avaliable in `CefSharp v111.2.20` or greater.
