### ISSUE TITLE
Crash after accepting cookies from opened link

### ISSUE THREAD

**Issue by youphorst** [SafeExamBrowser/seb-win-refactoring#576] opened 2023-02-27 16:09 UTC
**Describe the Bug**
One of the users of our assessment platform has reported an issue with the use of URLs which are opened in SEB. It seems that SEB crashes once cookies are accepted on the website which is allowed by whitelisting of URLs.

**Steps to Reproduce**
1. Whitelist URL
2. Start SEB
3. Click on URL
4. Allow cookies
5. Retry to open website a few times
6. SEB crashes

Video and logfiles have been attached to show the behavior.

**Expected Behavior**
I would expect SEB to be working, regardless whether cookies are accepted or not.
**Version Information**
 - SEB Versio 3.3.1 on Windows machine, but happens on other devices as well.
[2023-02-23_10h51m54s_Browser.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/10841602/2023-02-23_10h51m54s_Browser.log)
[2023-02-23_10h51m54s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/10841603/2023-02-23_10h51m54s_Client.log)
[2023-02-23_10h51m54s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/10841604/2023-02-23_10h51m54s_Runtime.log)

https://user-images.githubusercontent.com/123061996/221616515-24024358-c7b8-47fa-acd1-123b47412c34.mp4

**Comment by dbuechel** [comment] 2023-03-03 16:54
Thanks for your report. May I inquire how you determined that SEB crashes due to accepting cookies? We have had another report of a problem which appears related to yours (see #522) where the crash also happens to occur when closing an additional browser window. However, there the underlying reason seems to be an issue in the browser engine itself (see https://github.com/SafeExamBrowser/seb-win-refactoring/issues/522#issuecomment-1363309556).

**Comment by dbuechel** [comment] 2023-03-03 16:55
Did you try to reproduce the crash with the latest official release version 3.4.1? And as the issue appears to be related to the browser engine as well, you may want to test the latest beta build of the upcoming version 3.5.0 as well: https://sebdev-let.ethz.ch/api/buildjobs/ay1ugb1o8vl984ga/artifacts/SEB_3.5.0.525_SetupBundle.exe.

**Comment by dbuechel** [comment] 2023-03-14 15:54
As already stated, I suspect this to be an issue in the browser engine itself. We could verify this by obtaining the crash log entries in the Windows event viewer, specifically any error entries related to SEB in "Windows Logs" > "Application".

I myself am still unable to reproduce the issue, I just again attempted to reproduce it with the latest beta build of SEB 3.5.0. As I just yesterday updated the browser engine, could you please retry with that latest build to see whether the update may already have solved the issue: https://sebdev-let.ethz.ch/api/buildjobs/uyd16x0der6qis3u/artifacts/SEB_3.5.0.536_SetupBundle.exe.

**Comment by dbuechel** [comment] 2023-03-14 15:58
>They concluded that the issue is caused by cookies, as SEB crashed shortly after accepting cookies.

That would then most definitely be an issue in the browser engine. Did they encounter any related log entries in the SEB browser log or how exactly did they determine that it was the problem pertains to the cookie handling within the engine?

**Comment by dbuechel** [comment] 2023-03-14 15:59
To furthermore determine definitively whether it is an issue in the engine itself or not, one can try to reproduce the problem in the CEF sample application available here: https://cef-builds.spotifycdn.com/index.html.

**Comment by youphorst** [comment] 2023-03-15 11:04
Dear Damien,

I can't get the latest version you sent working. I get an error message which seems to be related to the way we configured the login process into SEB. We take the credentials which the participant used to login to our platform and use them to get the participant logged in directly. This seems to be another issue. I've included a screenshot and the logfile as reference.

I'll do some additional testing with the CEF sample application.

[2023-03-15_11h39m39s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/10978861/2023-03-15_11h39m39s_Runtime.log)
![IMG_0527](https://user-images.githubusercontent.com/123061996/225290395-9adaac3e-faf1-4507-98c9-dd358d9ec41d.JPG)


Kind regards,
Youp

**Comment by dbuechel** [comment] 2023-03-15 19:25
Terribly sorry, as the log shows me, there is an error with a custom user agent we added to the requests for downloading configuration files. I'll fix this asap and report back here once you can re-test with the latest beta version.

**Comment by youphorst** [comment] 2023-03-24 07:33
Hi Damian,

I've tested it again and this time I managed to reproduce the situation that our customer got. I tested it on your latest 3.5 version. By the way, I do get the same message even without doing anything with the cookies. So I guess the problem isn't related to cookies perse. However it is not correct that the session quits after all.
I've included a video and logfiles of the attempt with accepting cookies, but as said above, I have the same result when I leave the cookies untouched. My apologies for the quality of the video. I have the original file if you need it, but Github limits to 10MB. 

[2023-03-24_08h14m21s_Client.zip](https://github.com/SafeExamBrowser/seb-win-refactoring/files/11059490/2023-03-24_08h14m21s_Client.zip)


https://user-images.githubusercontent.com/123061996/227454306-aea5cdd7-9b10-489f-9663-0b462ccf824f.mp4



Best,
Youp

**Comment by dbuechel** [comment] 2023-03-24 17:32
Thanks for the update, I'll try to have another look at it next week.

**Comment by dbuechel** [comment] 2023-03-28 07:56
Thanks a lot, I have finally been able to reproduce this issue! It may be that it relates to another, similar issue which I unfortunately haven't been able to reproduce (#522) so we might be able to resolve both with a potential fix.

It appears there is a bug in the browser control implementation:

```
Application: SafeExamBrowser.Client.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at SafeExamBrowser.Browser.BrowserControl.get_CanNavigateForwards()
   at SafeExamBrowser.Browser.BrowserWindow.Control_LoadingStateChanged(Boolean)
   at SafeExamBrowser.Browser.BrowserControl.<Initialize>b__31_14(System.Object, CefSharp.LoadingStateChangedEventArgs)
   at CefSharp.WinForms.Handler.LoadHandler.OnLoadingStateChange(CefSharp.IWebBrowser, CefSharp.LoadingStateChangedEventArgs)
   at <Module>.CefSharp.Internals.ClientAdapter.OnLoadingStateChange(CefSharp.Internals.ClientAdapter*, scoped_refptr<CefBrowser>*, Boolean, Boolean, Boolean)
```

I'll try to fix the issue asap so that we may have it resolved with the upcoming release version 3.5.0 already.

**Comment by dbuechel** [comment] 2023-03-28 07:59
@youphorst Would you mind providing the error entry from the Windows Event Viewer application? This would help tremendously in determining whether the issue stems from the same place in all cases. The respective error log(s) should be under "Windows Logs" > "Application".

**Comment by youphorst** [comment] 2023-03-28 09:23
Hi Damian,

Nice that you also managed to reproduce the issue. I found 2 errors in the Windows Event Viewer of last Friday around 8:15 caused by SEB. See attached the logs. Can you confirm whether this is what you're looking for?

If you need any other information please let me know. Thanks again for investigating. 
[Windows event error logs.evtx.zip](https://github.com/SafeExamBrowser/seb-win-refactoring/files/11087668/Windows.event.error.logs.evtx.zip)

Kind regards,
Youp

**Comment by dbuechel** [comment] 2023-03-28 12:53
Excellent, thanks for the quick response. Yes indeed, it does appear that it is the same reason of failure for you as well. I hope that I was able to fix the issue, could you please retest the latest beta version: https://sebdev-let.ethz.ch/api/buildjobs/du6h6x4a9duy0bd6/artifacts/SEB_3.5.0.543_SetupBundle.exe.

**Comment by youphorst** [comment] 2023-03-30 09:41
Hi Damian,

We can confirm that the issue has been resolved in the latest beta version that you shared in your previous comment. Thanks for your actions to resolve the problem.

Could you please let us know when you are planning to release this version out of beta?

Kind regards,
Youp

**Comment by dbuechel** [comment] 2023-04-03 08:05
Excellent, that's great to know. We'll release SEB 3.5.0 no later than by the end of this week.

**Closed by dbuechel** 2023-04-03 08:05 UTC
Labels: bug
