### ISSUE TITLE
SEB Version 3 for Windows lacking X-SafeExamBrowser-RequestHash - Header after Redirect from IDP

### ISSUE THREAD

**Issue by swiniker** [SafeExamBrowser/seb-win-refactoring#241] opened 2021-11-10 08:06 UTC
**Describe the Bug**
If SwitchAAI/EduID is used to log into the exam system after log-in, when the browser is redirected to the exam-system, the "X-SafeExamBrowser-RequestHash"-Header is missing (and by the way also the config-Header). This leads to a Access-Denied if you check for the Hash on every request. The corresponding system works perfectly well with SEB 2.4.1 for Windows and 3.0 for MacOS.

**Steps to Reproduce**
1. Find a system using SwitchAAI or EduID for log-in
2. Log all requests
3. Log-in to the system
4. Check the headers sent to the Server on the redirect from the IdP.

**Expected Behavior**
The "X-SafeExamBrowser-RequestHash"-Header should be present.

**Version Information**
 - OS: Windows 10
 - SEB-Version: 3.x (I didn't test all iterations, but on any version I tested the problem existed.)

**Additional Context**
We are using ILIAS with a rewritten version of the SEB-Plugin (new rewrite for ILIAS 7: https://github.com/HochschuleLuzern/SEB/tree/ilias7 ). Don't hesitate to contact me if I can do anything to help.

**Comment by michaelhq** [comment] 2021-11-10 09:18
Hello everyone

I could reproduce the problem with the current Windows version of the SEB (3.3.1.388) and the Moodle of the FHNW. 

After redirecting from the eduID login directly to the test activity, it is not possible to start the test immediately. It displays, "This quiz has been configured so that students may only attempt it using the Safe Exam Browser." And the "Back to the course" button. But after reloading the page, you can start the test (reload must be allowed in the configuration). I guess that with reload the header is transmitted correctly.

This problem does not exist with the macOS version of the SEB.

Regards
Michael

**Comment by dbuechel** [comment] 2021-11-10 13:30
Thanks for the detailed report and investigations. We had to change the implementation due to #46 and also had other users reporting similar issues due to that change (see #66). If the CORS issue is indeed the root cause here, then I'm afraid that we can't fix it as it would fundamentally break websites like YouTube, Twitter et al.

However, we will release a new JavaScript API to query BEK and CK with the next release version. It is already implemented in the current beta build, so you might want to give that a try (see also #84).

**Comment by dbuechel** [comment] 2021-11-11 09:01
Okay, then I'd suggest to close the issue for now. But please feel free to reopen it in case you have new information.

**Closed by dbuechel** 2021-11-11 09:01 UTC
