### ISSUE TITLE
SEB on Windows reconfigures and doesn't show "Start Exam" button

### ISSUE THREAD

**Issue by a-camacho** [SafeExamBrowser/seb-win-refactoring#233] opened 2021-11-03 09:39 UTC
**Describe the Bug**
When creating a SEB config file, and uploading it to a quizz, students can access this quizz without any problem using Mac OS X. Using Windows, students click on "Start Safe Exam Browser" which launches SEB, they login and then on exam page they don't see "Start Exam" button. Weirdly, if they reload the page the button shows ...

_That also seems to reconfigure SEB when students arrive on the exam page, even if SEB is using the right exam configuration ... which drives SEB to reconfigure using same SEB file._

**Steps to Reproduce**
1. Create a quizz on moodle, and upload a simple SEB start exam file
2. Use SEB 3.3.1 on Windows, and try to start exam
3. Moodle "Start Quizz" button doesn't show right away, but a reload show it.
4. _SEB is also reconfigured (because it doesn't detect using already the right config file) which drives student to login twice_

**Expected Behavior**
SEB 3.3.1 on Windows, should show the Start Exam button right away (as it seems to show it afterwards, so doesn't seem to be a problem of invalid SEB file).

**Version Information**
 - OS: Windows 10
 - SEB-Version 3.3.1

**Comment by dbuechel** [comment] 2021-11-10 17:08
Thanks for your report. I think #241 is describing the underlying issue, we'll have to see whether there is a solution to it.

**Comment by dbuechel** [comment] 2022-05-20 16:15
@a-camacho Could you please try to reproduce the issue with the latest, official release version as well as with the latest development build for version 3.4.0, or better yet provide access to a Moodle quiz where the issue can be reproduced? I tried to debug the issue with our demo Moodle, but am somehow able to start the exam without the issue described above.

**Comment by dbuechel** [comment] 2022-05-31 12:44
We haven't been able to reproduce the issue. If there's no feedback until the final sprint before release of version 3.4.0, we'll have to close this due to lack of feedback.

**Comment by a-camacho** [comment] 2022-06-07 07:18
Hello.

Sorry for the delayed answer.

We did some assessments using students computers (both Mac OS and Windows) and did not see this problem again. I suppose students have updated their Safe Exam Browser, and the issue really seems fixed.

I will get back to you if we see this issue again.
Thanks a lot for your work !

**Comment by dbuechel** [comment] 2022-06-07 07:22
Excellent, that's good to know. Then we'll close this issue, but please feel free to reopen it or create a new one in case the issue would arise again.

**Closed by dbuechel** 2022-06-07 07:22 UTC
Labels: won't fix
