### ISSUE TITLE
Error 0x80070490: Failed to find expected public key in certificate chain.

### ISSUE THREAD

**Issue by DennisVH** [SafeExamBrowser/seb-win-refactoring#139] opened 2021-08-02 11:34 UTC
Same as #138 but in English
`[139C:1560][2021-08-02T13:18:00]i338: Acquiring package: WebView2_Bootstrapper, payload: WebView2_Bootstrapper, download from: https://go.microsoft.com/fwlink/p/?LinkId=2124703`
`[22B4:0660][2021-08-02T13:18:01]e000: Error 0x80070490: Failed to find expected public key in certificate chain.`
`22B4:0660][2021-08-02T13:18:01]e000: Error 0x80070490: Failed to verify expected payload against actual certificate chain.` 
`[22B4:0660][2021-08-02T13:18:01]e000: Error 0x80070490: Failed to verify signature of payload: WebView2_Bootstrapper`
`[22B4:0660][2021-08-02T13:18:01]e310: Failed to verify payload: WebView2_Bootstrapper at path: C:\ProgramData\Package Cache\.unverified\WebView2_Bootstrapper, error: 0x80070490. Deleting file.`
`[22B4:0660][2021-08-02T13:18:01]e000: Error 0x80070490: Failed to cache payload: WebView2_Bootstrapper`
`[139C:1560][2021-08-02T13:18:01]e314: Failed to cache payload: WebView2_Bootstrapper from working path: C:\Windows\Temp\{89546457-20C3-4743-A4D6-56870054A7F4}\WebView2_Bootstrapper, error: 0x80070490.`
`[139C:1560][2021-08-02T13:18:01]e349: Application requested retry of payload: WebView2_Bootstrapper, encountered error: 0x80070490. Retrying...`

Tried pre-installing Microsoft Edge WebView but still same installation issue

**Comment by marat123456** [comment] 2021-08-02 11:50
такая же проблема

**Comment by thankphuoc** [comment] 2021-08-02 12:59
Same problem. 
[Safe_Exam_Browser_20210802195529.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/6917042/Safe_Exam_Browser_20210802195529.log)

**Comment by danschlet** [comment] 2021-08-02 13:03
Deactivate anti-malware software which is scanning encrypted (https) internet traffic or other proxy or network analyzing software you might have installed.

The SEB and the installers of the dependencies connect to Microsoft servers and use certificate pinning. Such above mentioned tools replace the root CA certificates in Windows to perform a Man-in-the-Middle attack to be able to analyze encrypted network connections. Those installers fail then.

**Comment by marat123456** [comment] 2021-08-02 13:29
Антивирусов нет, только брандмауэр windows и его я полностью отключил. Проблема не ушла.

**Comment by danschlet** [comment] 2021-08-02 13:32
Just for your information: We can give support to requests in English, German, Spanish and French. Russian is not a supported language, I'm sorry.

**Comment by marat123456** [comment] 2021-08-02 13:33
The antivirus is disabled. The problem has not disappeared

**Comment by danschlet** [comment] 2021-08-02 13:38
Maybe @dbuechel can help.

**Comment by marat123456** [comment] 2021-08-02 13:39
here is my log file
[Safe_Exam_Browser_20210802145528.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/6917311/Safe_Exam_Browser_20210802145528.log)

**Comment by dbuechel** [comment] 2021-08-02 19:28
Microsoft has updated their WebView2 bootstrapper (yet again). @danschlet We might need to switch to a fixed-version setup as we already have it with CefSharp.

For the meantime: To use SEB 3.2.0, first install all the required dependencies as listed below:

- .NET Framework 4.7.2 Runtime: https://dotnet.microsoft.com/download/dotnet-framework/net472
- Microsoft Edge WebView2 Runtime: https://go.microsoft.com/fwlink/p/?LinkId=2124703
- Visual C++ 2015-2019 Redistributable: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

Then install the SEB 3.2.0 MSI for your platform (either x86 for 32-bit or x64 for 64-bit machines):

- https://github.com/SafeExamBrowser/seb-win-refactoring/releases/download/3.2.0/SEB_3.2.0.338_x64_Setup.msi
- https://github.com/SafeExamBrowser/seb-win-refactoring/releases/download/3.2.0/SEB_3.2.0.338_x86_Setup.msi

**Comment by danschlet** [comment] 2021-08-03 10:30
> Microsoft has updated their WebView2 bootstrapper (yet again). @danschlet We might need to switch to a fixed-version setup as we already have it with CefSharp.

Yes, please do that @dbuechel, seems like the only way how to prevent issues with these Microsoft updates.

**Comment by dbuechel** [comment] 2021-08-03 11:47
The issue is now fixed with the latest release version 3.3.0.

**Closed by dbuechel** 2021-08-03 11:47 UTC

**Comment by nebuduk** [comment] 2021-08-03 13:16
Installation worked fine, thank you very much for your promt help and answer!

**Comment by souviksenapati** [comment] 2021-12-14 18:56
I still have same issue with version 3.3.0.354
![Error](https://user-images.githubusercontent.com/47359760/146061840-bc7cc1d5-16fe-4c69-9c72-f237b010b3d5.png)
[Safe_Exam_Browser_20211215000337.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/7714089/Safe_Exam_Browser_20211215000337.log)
