### ISSUE TITLE
SEB fails to start: Communication channel has faulted

### ISSUE THREAD

**Issue by MyonNeutrino** [SafeExamBrowser/seb-win-refactoring#555] opened 2023-01-16 14:14 UTC
**Describe the Bug**
When trying to start the safe exam browser it crashes, displaying a hint to look into the log files.

**Steps to Reproduce**
1. Have Windows 10 installed with a long history of unreproducable changes.
2. Install SEB
3. Try to start SEB

**Expected Behavior**

Either of:

- SEB starts normally
- SEB suggests the required settings for it to work properly so that a non-windows-specialist can apply them.
- SEB automatically does the neccessary configuration during the setup process or warns about missing dependencies or system access rights
- SEB uses a different approach to inter process communication on windows devices that is accessable on every machine
- SEB asks for Administrator rights when missing privileges

**Screenshots**
![SEB-Crash](https://user-images.githubusercontent.com/10752614/212692601-79474ac4-f1fb-48dd-b9d9-67be98ae1b40.PNG)

**Version Information**
 - OS: Windows 10, Microsoft Windows NT 10.0.19045.0 (x64)
 - SEB-Version: Version 3.4.1 (x64), Build 3.4.1.505

**Additional Context**
Log files:

- [2023-01-16_14h10m50s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/10426382/2023-01-16_14h10m50s_Client.log)
- [2023-01-16_14h10m50s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/10426384/2023-01-16_14h10m50s_Runtime.log)

I worked around this issue by installing a new instance of windows 10. So it is not pressing to me. But i have seen a couple of other Issues here that got closed without really resolving them or having explicit steps how to.

- #479 
- #509 
- discussion: #513 

This bug report is not only about the initial crash but also about the way it is handled. I do see that it is opinionated. You cannot control every possible environment under the sun. But you could check whether or not the technologies or privileges you use are available on the targeted systems.

**Comment by danschlet** [comment] 2023-01-16 14:42
The general problem is that Windows is a messy operating system where developers cannot rely on even basic frameworks to work correctly. Ask professional system administrators and they will confirm this. We are nevertheless working constantly to improve SEB. As this software is free and our resources limited, feel free to contribute to its development by joining the SEB Alliance (or convincing your exam organizing body to do so).

**Comment by MyonNeutrino** [comment] 2023-01-16 15:10
I totally understand and do not envy you. I do appreciate the work you do and, from what i can tell so far, I do like the working product after a fresh windows install. I just hope this to be helpful at some point. So thank you!

**Comment by danschlet** [comment] 2023-01-16 15:31
Thank you for your understanding. It definitely is disappointing (also for us) that such issues happen depending on the state of the Windows installation and that there doesn't seem to be a reliable way to install the software so everything works without manual fixes. I assume that this happens more often to .NET applications (less to Win32, UWP, WinRT ?) and maybe because we're using not so common frameworks, but that's just a speculation and what some system administrators told us. @dbuechel might know more about that. We will definitely investigate issues further if we have some leads how to fix those and any feedback is welcome.

**Comment by danschlet** [comment] 2023-01-16 17:25
@dbuechel might have more information about this, he can contact you in February when he's back from his leave. I remember a case when actually a very old SEB version had a generic name for the named pipe it's using, which then interfered with another application which was also using named pipes. That issue was then solved with SEB, but it showed that the named pipes system can be broken by some app which doesn't use it properly.

**Comment by dbuechel** [comment] 2023-02-06 17:18
The issue with the name conflict for the pipes definitely has been resolved with SEB 3.x, see https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SafeExamBrowser.Configuration.Contracts/AppConfig.cs#L27 (unless there is another software using "safeexambrowser" in their pipe address...).

However, as already correctly mentioned above, Windows is a huge ecosystem with myriads of different possible hardware and software configurations. Given the extremely limited resources we have, we simply cannot guarantee that SEB works without issues on all of them. There may be software (e.g. anti-virus software, screen recording or meeting software, mods etc.) which interferes with SEB, there may be system-wide configuration options which interfere with SEB, there may be system management software on managed devices which interfere with SEB and so on. And, if I may hazard a guess, sometimes if not often there are end users wrecking their system or its configuration by not really knowing what they are doing when e.g. changing a system configuration parameter, installing or uninstalling software and what not.

Attempting to solve an issue like this one remotely is pretty hard, and any success in doing so is completely depending on the information we get provided. The more accurate and complete an issue report, the more likely we're able to actually reproduce and then attempt to fix the problem. However, there really are issues which simply cannot be resolved without being physically in front of the system where the problem occurs, and I'm afraid this might just be one of these rare issues.

I'd happily try to investigate the issue further, but therefor I'd at least need the following information to do so meaningfully:

1. A screen recording showing the entire boot procedure up and until starting SEB and encountering the error message.
2. A list of all installed software on the system with the issue.
3. A list of all actually running software and utilities when SEB is attempted to be started.
4. All Windows event logs.
5. All SEB logs.

**Closed** 2023-03-14 17:06 UTC
Labels: being investigated

**Comment by JA-HTL** [comment] 2024-04-05 12:05
We do have the same issue on a computer with windows 11. Is there a possibility to get a more detailed log?

[2024-04-05_13h35m25s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/14884539/2024-04-05_13h35m25s_Client.log)
[2024-04-05_13h35m25s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/14884540/2024-04-05_13h35m25s_Runtime.log)
![Bild_2024-04-05_133917988](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/82495538/0a0b4014-36b1-4b6c-a37b-b842b68d6e9d)

**Comment by dbuechel** [comment] 2024-04-05 15:57
@JA-HTL There might be additional information in the system event logs (using the Event Viewer application), specifically under "Windows Logs" > "Application").

We most unfortunately have thus far not received any meaningful event log entries nor were we able to determine what the underlying cause might be.

**Comment by JA-HTL** [comment] 2024-04-08 05:42
The problem ist on a students laptop, I try to get the logs from him. In the meantime I have a video of the starting process, maybe that helps a little

https://github.com/SafeExamBrowser/seb-win-refactoring/assets/82495538/8ee34882-cc14-4e31-881e-3d04ca4bcd35

**Comment by dbuechel** [comment] 2024-04-08 13:15
@JA-HTL Thanks for the video, though it would be great if you could record the entire startup procedure (from where and how SEB itself is being started etc.).

**Comment by dbuechel** [comment] 2024-04-11 11:01
Please use issue #824 for all further discussion.
