### ISSUE TITLE
Problem with starting SEB because Virtual machine recognised

### ISSUE THREAD

**Issue by ITNKSA** [SafeExamBrowser/seb-win-refactoring#904] opened 2024-06-05 10:28 UTC
SEB dont start because Virtual machine recognised but its normal Windows 11 pro version installed.
The Laptop was rebuilt with an image from old Laptop.

![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/144320733/f2f23fca-5d07-4bf8-89f4-084aca8d1900)

![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/144320733/4748423c-0bf8-4cd1-9027-ced2a235eeb5)

**Comment by spicymoodles** [comment] 2024-06-06 06:13
What happens if you tick "Allow to run in VM" in the Security tab?

**Comment by ITNKSA** [comment] 2024-06-06 06:38
I've never seen this option. Where is the Security tab?

**Comment by spicymoodles** [comment] 2024-06-06 09:05
Sorry, are you trying to set up SEB using the config tool? 
In any case, the setting is here:

![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/126999106/c5559b9b-8bd3-4c10-9006-41d96488ded6)

**Comment by ITNKSA** [comment] 2024-06-06 09:53
Our students start SEB with exam.net. Thye dont use config tool. And its not allowed to run SEB with virtual machine. But thsi laptop is not a virtual machine. Thats the problem!

![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/144320733/24469713-c916-4bd1-82a5-f770ab4f7028)

![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/144320733/add349bc-4c97-4ef1-a577-47d63555badf)

The configuration is in exam.net:

![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/144320733/fee934d5-a311-4440-a66a-8322df4b2d02)

![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/144320733/78fac497-ee14-4a47-9624-528c8d171612)

**Comment by spicymoodles** [comment] 2024-06-06 12:17
Does this only happen on the laptop? 
Is the laptop a touch screen? Maybe disable the touch screen to see if that is the cause..

**Comment by ITNKSA** [comment] 2024-06-06 12:21
Yeah its only one laptop you can see systeminformations in first post. 
We are a school with arround 1000 BYOD laptops. And all of them are using exam.net a lot. And they all have touchscreens. we cant disable touch screen every time the student will have a exam.

Why does SEB belive that its a virtual machine without being it?

**Comment by spicymoodles** [comment] 2024-06-06 12:28
Not sure, if it's only happening on 1 BYOD I wouldn't bother...
 Might be worth re-installing windows from scratch not image. 
 
 Sorry I'm not a SEB developer, i'm a SEB user like yourself.

**Comment by ITNKSA** [comment] 2024-06-06 12:32
Ah i thought your somebody from eth. so thank you very much for support

**Comment by dbuechel** [comment] 2024-06-07 08:06
@ITNKSA Please provide the log files of the affected session(s). They can be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Comment by ITNKSA** [comment] 2024-06-10 11:57
[SEB Logs C. Wendler.zip](https://github.com/user-attachments/files/15765189/SEB.Logs.C.Wendler.zip)

**Comment by dbuechel** [comment] 2024-06-12 09:20
The logs are a bit contradictory, because it appears that you have been able to start SEB a few times, though mostly not:

```
2024-06-03 13:49:17.097 [04] - INFO: Validating virtual machine policy...
2024-06-03 13:49:17.101 [04] - DEBUG: [VirtualMachineDetector] Computer 'PAVILION-X360' appears not to be a virtual machine.
```

```
2024-06-03 13:28:20.319 [06] - INFO: Validating virtual machine policy...
2024-06-03 13:28:20.343 [06] - WARNING: [Registry] Failed to get sub keys for 'HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\TaskFlow\DeviceCache'.
2024-06-03 13:28:20.344 [06] - DEBUG: [VirtualMachineDetector] Computer 'PAVILION-X360' appears to be a virtual machine.
2024-06-03 13:28:20.345 [06] - ERROR: Detected virtual machine while SEB is not allowed to be run in a virtual machine! Aborting...
```

As to why that would be is unclear to me. We however made a few changes to the VM detection due to other false-positive detections, thus please try the latest beta version of SEB 3.8.0 to see whether these fix your issue as well: https://sebdev.ethz.ch/api/buildjobs/3j031h1akri33g9y/artifacts/SEB_3.8.0.697_SetupBundle.exe.

**Comment by dbuechel** [comment] 2024-06-12 09:22
@Notselwyn What are your thoughts regarding the device cache key, which appears to trigger a detection when it can't be read?

**Comment by dbuechel** [comment] 2024-06-12 10:09
Thanks, that's good to know. It is either way weird (if not suspicious) that it has worked a few times and then again not...

**Comment by ITNKSA** [comment] 2024-06-12 10:27
@dbuechel We had installed SEB 3.4.0 Version for testing and than it worked, but thats not the newest version and so not allowed to use in our school. maybe the log is from version 3.4

**Comment by ITNKSA** [comment] 2024-06-12 11:35
> The logs are a bit contradictory, because it appears that you have been able to start SEB a few times, though mostly not:
> 
> ```
> 2024-06-03 13:49:17.097 [04] - INFO: Validating virtual machine policy...
> 2024-06-03 13:49:17.101 [04] - DEBUG: [VirtualMachineDetector] Computer 'PAVILION-X360' appears not to be a virtual machine.
> ```
> 
> ```
> 2024-06-03 13:28:20.319 [06] - INFO: Validating virtual machine policy...
> 2024-06-03 13:28:20.343 [06] - WARNING: [Registry] Failed to get sub keys for 'HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\TaskFlow\DeviceCache'.
> 2024-06-03 13:28:20.344 [06] - DEBUG: [VirtualMachineDetector] Computer 'PAVILION-X360' appears to be a virtual machine.
> 2024-06-03 13:28:20.345 [06] - ERROR: Detected virtual machine while SEB is not allowed to be run in a virtual machine! Aborting...
> ```
> 
> As to why that would be is unclear to me. We however made a few changes to the VM detection due to other false-positive detections, thus please try the latest beta version of SEB 3.8.0 to see whether these fix your issue as well: https://sebdev.ethz.ch/api/buildjobs/3j031h1akri33g9y/artifacts/SEB_3.8.0.697_SetupBundle.exe.

The student installed the SEB 3.8.0 Version and now it works :) ... Thank you very much!

**Comment by dbuechel** [comment] 2024-06-12 12:09
Great, then this indeed will be fixed with the upcoming release.

**Closed by dbuechel** 2024-06-12 12:09 UTC
Labels: being investigated
