### ISSUE TITLE
Shibboleth-based (AAI) SSO random loops when using a template version

### ISSUE THREAD

**Issue by hribeir0** [SafeExamBrowser/seb-win-refactoring#284] opened 2021-12-13 13:01 UTC
Hi all,
We are using Moodle 3.9 and SEB 3.2.0 (and have already tried with 3.3.1 to the same results). We have several managed computers with the same sw (installed via imaging sw). Students use Shibboleth-based (AAI) SSO authentication while on exam setting. Our teachers select a SEB provided template in Moodle.

The problem:
- randomly, some users are unable to log-in via AAI because after entering their credentials they go back to the login screen, and end up in a loop.

This happens totally randomly and I'm unable to reproduce... There's no issues if students login directly in moodle.

Any idea?

**Comment by dbuechel** [comment] 2021-12-15 09:46
On first sight, this doesn't appear to have anything to do with SEB. Did you check the application logs and verify that the same behavior doesn't occur as well with e.g. Chrome?

**Comment by hribeir0** [comment] 2021-12-15 14:55
Will check logs since there's also another recurring issue when seb freezes while open a new session (with the green bar moving). While this isn't as bad as the mentioned problem, I'll try to check the logs later for both issues.
Is important to mentioned that we've changed Moodle SEB settings into manual config and the first issue (looping in the authentication process) disappeared what makes me suspect of the seb conf settings. On the other hand not every students have to deal with this issue. Maybe only 10%. 
It's hard to check everything since we are dealing with 100s of students in a high stake, high pressure assessment...

**Comment by dbuechel** [comment] 2022-01-07 10:42
@hribeir0 Any updates on this issue?

**Comment by hribeir0** [comment] 2022-01-07 12:24
I wasn't able to check the logs. However, the mentioned issue of freezing while starting seb session still occurs while using Moodle manual SeB config and if students choose "Launch Seb". It doesn't happen if they download seb config file and then open it. Have you ever heard of anything similar?

**Comment by dbuechel** [comment] 2022-01-07 16:16
I do not recall anything similar at the moment, but we have an internal meeting related to AAI issues next week. It might be that these are all linked together and will be fixed with the other issues, but as long as we don't have a reliable way to reproduce this particular problem, there unfortunately isn't much we can do.

**Comment by hribeir0** [comment] 2022-01-07 18:11
Thanks. I understand, that's our pain also. 
Today we had another exam using Moodle Manual settings (everything standard) and some computers froze while trying to open the session (I have a couple of photos) with the green bar moving. I was sent logs from 3 different computers where this happened. Where should I look into? (Bear in mind that after exiting and relaunching SEB via config file, students were able move forward)

**Comment by dbuechel** [comment] 2022-01-10 11:47
The runtime or client log file should definitely provide you with starting points. If a component of SEB crashed, then you should furthermore be able to find the exact details of the crash in the Windows event logs.

**Comment by dbuechel** [comment] 2022-01-27 14:35
@hribeir0 Did you gain any insights in the meantime, or do you happen to have any log files we could study further?

**Comment by hribeir0** [comment] 2022-01-28 18:18
So the logs do have some errors but I believe it's for the best that you take a look. These are logs from 2 different quizzes, but both are using Seb manual settings on Moodle.
I have separated them by success on first try and on second try. Those who were able to succeed launched SEB, got session freeze (trying to start the session) and then had to quit and download the seb file. Then were able to proceed.
[1st try success](https://elearning.up.pt/seb-logs/1st-try-success.zip)
[2nd try success](https://elearning.up.pt/seb-logs/2nd-try-success.zip)

Thank you very much

**Comment by dbuechel** [comment] 2022-02-01 08:56
Okay, excellent. We have scheduled this issue for the next release version 3.4 and I'll thus have a look at the logs in the coming weeks.

**Comment by dbuechel** [comment] 2022-08-03 15:08
Terribly sorry for the late response, we were extremely busy with other priorities and pending work for SEB 3.4. I have studied the log files, however was unable to find any particular issue. The only abnormality I could see was the hang of "fcnaup-1204d03", however there are unfortunately no indications on why it had occurred.

Do you have any further information or a reliable way to reproduce the issue? If not, I'm afraid that we won't be able to do much as we'd need to be able to reproduce the problem in order to attempt to resolve it.

**Closed** 2022-08-17 13:01 UTC

**Comment by WilliamDelamare** [comment] 2022-11-15 20:39
Hi!
We are currently encountering the same problem: loop at moodle login with our own configuration from the SEB configurator app. But the authentication is with Microsoft, and no template (just uploading a `.seb` file in the Moodle corresponding field)

At first, I thought it was because I forgot to allow login.microsoftonline URLs. But no.

What we tried so far with the current config file:
- 1 fake student account with standard Moodle sign-in: ok
- 1 Teacher account with Microsoft sign-in: ok (but of course, the Moodle page shows the teacher's view)
- 1 fake + 2 real student accounts with Microsoft sign-in: loop


To be clear, when I say "loop", it is SEB just restarting over and over and landing on the sign-in page.

Although our problem is clearly related to the original post, let me know if you want me to open a new issue because of some differences (i.e., no template, microsoft login).

**Comment by dbuechel** [comment] 2022-11-17 13:51
This sounds more like a configuration issue to me. Are you sure that SEB e.g. doesn't land on a page after login where he's instructed to immediately reconfigure itself (again and again), thus ending up in an endless loop?

**Comment by WilliamDelamare** [comment] 2022-11-17 15:40
Thanks for the reply.
I set the start URL to the moodle quizz page (with buttons to start SEB, or download SEB, or download SEB config).
Since this works with (1) a normal login, or (2) a microsoft (teacher) login, I assume the landing page was ok and did not create this loop.
But I agree that it might simply be a config problem since the logs do not show any errors. Just the service asking the client to shutdown, and then the client asking the service to shutdown, etc, but only in this particular case.

What kind of page do you think of that could instruct SEB to reconfigure itself?
I thought the SEB config was performed at launch and simply checked by webpages, not manipulated.

Let me know if you want to have a look at the log.

**Comment by WilliamDelamare** [comment] 2022-11-17 16:17
(I can still provide the log files and test for you if you want to investigate this aspect further.)

**Comment by dbuechel** [comment] 2022-11-17 16:21
Excellent, that's great news! Unfortunately, we don't have the capacity at the moment to keep investigating the reload issue (I think we had it reported before, but I don't remember exactly what the conclusion was back then).

So if it's working like this for you for now, then it'd be great if we can leave it at that for the moment. But if you want to have the reload issue recorded in the backlog, please do feel free to create a separate issue for it. We however most likely won't be able to have a look at it before next year.

**Comment by WilliamDelamare** [comment] 2022-11-17 16:33
Yes, it was reported in #233 and marked as closed with version 3.4.0 (the one I am currently using).
I will wait for all students to try the exam before re-opening the issue, just to see if it was localized to few setups or if it happens with everyone.
