### ISSUE TITLE
SEB starts after 3 Minutes

### ISSUE THREAD

**Issue by dkummer63** [SafeExamBrowser/seb-win-refactoring#1062] opened 2024-12-16 11:51 UTC
I have a strange case with a student with a brand new Lenovo device, Win11 Home, 24H2. When she starts the exam in exam.net with SEB 3.8, nothing happens for about 3 to 5 minutes. However, the SEB is listed as active in the task manager. 
After 3-5 minutes the SEB starts regularly in the exam and the exam can be written without further disturbances. However, it is a stress factor for the student to have to wait so long. 
The log files are attached. 
Thanks for any help! 

[2024-12-16_11h17m15s_Client.log](https://github.com/user-attachments/files/18149555/2024-12-16_11h17m15s_Client.log)
[2024-12-16_11h17m15s_Browser.log](https://github.com/user-attachments/files/18149556/2024-12-16_11h17m15s_Browser.log)
[2024-12-16_11h17m15s_Service.log](https://github.com/user-attachments/files/18149557/2024-12-16_11h17m15s_Service.log)
[2024-12-16_11h17m15s_Runtime.log](https://github.com/user-attachments/files/18149558/2024-12-16_11h17m15s_Runtime.log)

**Comment by danschlet** [comment] 2024-12-16 12:43
Duplicate of https://github.com/SafeExamBrowser/seb-win-refactoring/issues/1023#issuecomment-2545477313

**Closed by danschlet** 2024-12-16 12:43 UTC
