### ISSUE TITLE
Can't upload files when %userprofile% is on a network share

### ISSUE THREAD

**Issue by a-camacho** [SafeExamBrowser/seb-win-refactoring#229] opened 2021-10-25 14:41 UTC
**Describe the Bug**
When using version 3.0.0 of SEB for Windows, we have a big problem regarding downloading and uploading files.

We are using a VMWare-Windows environment, and recently have switched from "Persona Management" to "UEM".
- Old mechanics would "sync" user profile to an external network share
- New mechanics "mounts" the user profile on the machine (from network share)

Difference is users were working in `C:/Users/username` before, and are now working in a network share `\\isis.unige.ch\path\username` 

**Steps to Reproduce**
1. Use a windows virtual machine with user profile mounted from network (with UEM)
2. Open a SEB config file that allows upload/download
3. When looking for file to upload, SEB file explorer shows error and cannot show file in network share

**Expected Behavior**
File selection should work, on local machine but also on network share (if user has write access, and that it is correctly configured)

**Screenshots**
![capture](https://user-images.githubusercontent.com/29976133/138716635-614f1f69-d9d2-4663-a738-50d17ba88a3a.png)

**Version Information**
 - OS: Windows 10 (1809)
 - SEB 3.0.0

**Comment by a-camacho** [comment] 2021-11-29 10:39
Hi there.

We also saw that some software (RStudio) has a problem when launched from SEB. `RProfile.site` file is a default one not customized.

- When RStudio is launched outside SEB, RStudio makes the working directory as the user's home (`~`) without any problem.
- When RStudio is launched from SEB, it seems to fail working in this directory, and falls back to `C:\Windows`.

Could that problem relate to this issue with SEB and network locations ?
Thanks a lot.

**Comment by dbuechel** [comment] 2021-11-29 11:58
> Could that problem relate to this issue with SEB and network locations ?

As this is a third-party application, I rather doubt that. It might be a side-effect of the kiosk mode, which requires the Windows shell (i.e. explorer.exe) to be terminated.

**Comment by dbuechel** [comment] 2021-12-21 11:57
@a-camacho I am now unable to reproduce the issue, I don't know whether this was a bug in the framework or in Windows which has been fixed in the meantime. Could you please download the latest beta build of version 3.3.2 and try whether it works for you as well?

https://sebdev-let.ethz.ch/api/buildjobs/un3vu1ip67b3wvgo/artifacts/SEB_3.3.2.399_SetupBundle.exe

**Comment by dbuechel** [comment] 2022-01-06 09:38
Any updates here? Otherwise, we'd need to move this issue to version 3.4.0 as we'll need to release 3.3.2 once the other open issues are resolved.

**Comment by dbuechel** [comment] 2022-01-11 22:45
@a-camacho Were you able to reproduce the issue with the latest beta build?

**Comment by dbuechel** [comment] 2022-01-18 23:06
The issue should be fixed with the latest beta build: https://sebdev-let.ethz.ch/api/buildjobs/wbw4rhbif0181wg0/artifacts/SEB_3.3.2.409_SetupBundle.exe

**Closed as completed** 2022-01-31 16:54 UTC
Labels: bug
