### ISSUE TITLE
Disable Forbidden Cursor Configuration Checks for Screen Monitoring

### ISSUE THREAD

**Issue by simonatwork** [SafeExamBrowser/seb-win-refactoring#815] opened 2024-02-28 09:52 UTC
We are using a software called NetSupport School (also available under the name MasterSolution Suite XL on the german language market) to monitor local computers in a lab while conducting on-site tests / exams. The software allows us to keep an eye on all lab computer screens  at once. However, with the 3.6 version of SEB, opening up a screen on the master machine to view details triggers SEB to stop working with the "Forbidden Cursor Configuration detected" ("SEB gesperrt" --> "Eine verbotene Cursor-Konfiguration wurde detektiert.") warning message. This can be only unlocked by entering the quit / unlock password.

As these computers are on-premise and under our own control, we do not need these kind of checks as there is no way for students to run own software to share their screen with others for cheating. 

It would be great to be able to disable these cursor configuration checks so that we can continue using software for screen monitoring.

**Comment by strau0106** [comment] 2024-03-01 11:05
duplicate of #755. This is planned for [3.7.0](https://github.com/SafeExamBrowser/seb-win-refactoring/projects/11)

**Comment by dbuechel** [comment] 2024-03-05 09:36
Thanks for your input, this indeed will be resolved for the upcoming version 3.7.0.

**Closed** 2024-03-05 09:37 UTC
Labels: duplicate
